# Generated by Django 5.0.6 on 2026-06-25 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0, help_text='Stock allocated to pending orders but not yet shipped.')),
                ('minimum_stock_level', models.PositiveIntegerField(default=0, help_text='Reorder threshold. Below this triggers a low-stock alert.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_stockitem',
                'ordering': ['product__name'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=12)),
                ('quantity', models.PositiveIntegerField()),
                ('adjustment_delta', models.IntegerField(blank=True, help_text='Signed change applied for ADJUSTMENT transactions (can be negative).', null=True)),
                ('reference_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Only set for TRANSFER transactions: the warehouse stock is moving to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouses.warehouse')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.product')),
                ('warehouse', models.ForeignKey(help_text='Source warehouse for OUT/ADJUSTMENT/TRANSFER, or the receiving warehouse for IN.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_stocktransaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'created_at'], name='stock_stock_transac_d6832b_idx')],
            },
        ),
    ]
